variables:
  COMPILE_IMAGE: node:12.14-alpine
  ANSIBLE_IMAGE: ansible/centos7-ansible

cache:
  key: "$CI_PROJECT_NAMESPACE"
  paths:
    - node_modules

stages:
  - build
  - deploy

build_dev:
  only:
    - /^v\d+\.\d+\.\d+-dev$/
  stage: build
  image: $COMPILE_IMAGE
  artifacts:
    name: "${CI_COMMIT_TAG}"
    paths:
      - dist/
  script:
    - npm config set registry https://registry.npm.taobao.org/
    - npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/
    - npm install
    - npm run build
  allow_failure: false

deploy_dev:
  only:
    - /^v\d+\.\d+\.\d+-dev$/
  stage: deploy
  image: $ANSIBLE_IMAGE
  variables:
    GIT_STRATEGY: none
  script:
    - mkdir ~/.ssh/
    - echo -e "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - echo -e "${ANSIBLE_HOSTS}" > ~/hosts
    - echo -e "${ANSIBLE_PLAYBOOK}" > ~/playbook.yml
    - echo -e "${DEV_NGINX_PROXY}" > ./dist/nginx-proxy.conf
    - cd ./dist
    - tar zcf ../dist.tar.gz *
    - ansible-playbook ~/playbook.yml -i ~/hosts --extra-vars "{'server_name':'dev_server'}"
  allow_failure: false